# Generated by Django 5.0.4 on 2024-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0002_hf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hf',
            old_name='chol',
            new_name='DEATHEVENT',
        ),
        migrations.RenameField(
            model_name='hf',
            old_name='oldpeak',
            new_name='anaemia',
        ),
        migrations.RenameField(
            model_name='hf',
            old_name='thalach',
            new_name='cholcreatinine_phosphokinase',
        ),
        migrations.RenameField(
            model_name='hf',
            old_name='trestbps',
            new_name='diabetes',
        ),
        migrations.AddField(
            model_name='cad',
            name='ca',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad',
            name='cp',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad',
            name='exang',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad',
            name='fbs',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad',
            name='restecg',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad',
            name='sex',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad',
            name='slope',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cad',
            name='thal',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hf',
            name='ejection_fraction',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hf',
            name='high_blood_pressure',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hf',
            name='platelets',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hf',
            name='serum_creatinine',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hf',
            name='serum_sodium',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hf',
            name='sex',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hf',
            name='smoking',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hf',
            name='time',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
    ]
